name: CI/CD for Cosm Terminal App

on:
  push:
    branches:
      - '**'  # Run tests on all branches
    tags:
      - 'v*'  # Run build and release for tagged versions
  pull_request:
    branches:
      - '**'  # Run tests on pull requests to all branches

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run tests
        run: |
          if [ "${{ matrix.os }}" = "macos-14" ]; then
            GOARCH=arm64 go test ./... -v
          else
            GOARCH=amd64 go test ./... -v
          fi

  build-and-release:
    name: Build and Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access for creating releases
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: linux
            goarch: arm64  # Only linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run tests
        run: go test ./... -v

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o cosm-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags "-X main.version=${{ github.ref_name }}"
          chmod +x cosm-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Archive binary
        run: |
          if [ "${{ matrix.goos }}" = "linux" ]; then
            tar -czvf cosm-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz cosm-${{ matrix.goos }}-${{ matrix.goarch }}
          else
            zip cosm-${{ matrix.goos }}-${{ matrix.goarch }}.zip cosm-${{ matrix.goos }}-${{ matrix.goarch }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cosm-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            cosm-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
            cosm-${{ matrix.goos }}-${{ matrix.goarch }}.zip

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts for debugging
        run: |
          ls -R artifacts
          echo "Current directory contents:"
          ls -R

      - name: Create Release
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'  # Run release only once
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/cosm-linux-amd64/cosm-linux-amd64.tar.gz
            artifacts/cosm-darwin-amd64/cosm-darwin-amd64.zip
            artifacts/cosm-darwin-arm64/cosm-darwin-arm64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}